[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["solady/=lib/solady/src/", "forge-std/=lib/forge-std/src/", "@openzeppelin/=lib/openzeppelin-contracts/", "solmate/=lib/solmate/src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
